version: "3.5"

services:
  app:
    tty: true
    stdin_open: true
    image: lol
    container_name: react-app
    volumes:
      - /home/tryzo/Desktop/dev/my-app/src:/src
    ports:
      - "4000:4000"
    restart: unless-stopped